@apiUrl = http://127.0.0.1:8080

# Rest-Client kan läsa variabler ur .env
@api_key = {{$dotenv API_KEY}}

### Get all rooms
GET {{apiUrl}}/rooms

### Get all guests
GET {{apiUrl}}/guests

### Get bookings
GET {{apiUrl}}/bookings

### Create booking
POST {{apiUrl}}/bookings
Content-Type: application/json
X-API-Key: {{api_key}}

{
    "room_id": 2,
    "datefrom": "2026-06-01",
    "dateto": "2026-05-03",
    "info": "info..."
}

### Uppdatera bokning
PUT {{apiUrl}}/bookings/2
Content-Type: application/json
X-API-Key: {{api_key}}

{
    "stars": 4
}