# Kräver VSCode tillägget Rest-Client (humao.rest-client)
@apiUrl = https://fw-teaching.fi/demo/wdbocms/api/v1/products

### Get all products
GET {{apiUrl}}

### Get one product
GET {{apiUrl}}/1002

### Create new product
POST {{apiUrl}}
Content-Type: application/json

{
  "name": "Jeans",
  "price": 49
}

### Delete a product
DELETE {{apiUrl}}/1005

### Update a product (PATCH)
PATCH {{apiUrl}}/1001
Content-Type: application/json

{
  "price": 24.99
}

### Update a product (PUT)
PUT {{apiUrl}}/1001
Content-Type: application/json

{
  "price": 24.99
}